import type { RepositoryScan } from "@/types/repository";

// Sample scan used to develop and preview the Repository Explorer v2 screens.
export const SAMPLE_SCAN: RepositoryScan = {
  id: "repo-ai-review-sample",
  name: "ai-review-sample",
  scanMode: "device",
  scannedAt: new Date().toISOString(),
  verdict: {
    overallRisk: "high",
    trustStatus: "review-required",
    highestPathConfidence: "probable",
    summaryLine:
      "A path can reach your filesystem with write access — no approval step.",
    confirmedSummary: "wildcard permission + auto-approval on filesystem-mcp",
    inferredSummary: "prompt → router → MCP routing",
  },
  coverage: {
    considered: 433,
    scanned: 355,
    skipped: 78,
    productionArtifacts: 6,
    skippedBreakdown: { generated: 31, unsupported: 22, binary: 18, oversized: 7 },
  },
  findings: { confirmed: 2, probable: 2, potential: 5 },
  riskScore: 39,
  nextAction: {
    file: ".cursor/mcp.json",
    effort: "5 min",
    issueTitle: "Apply permission constraint in .cursor/mcp.json",
    before: '{ "filesystem-mcp": {\n  "autoApprove": true,\n  "permissions": ["*"]\n} }',
    after:
      '{ "filesystem-mcp": {\n  "autoApprove": false,\n  "permissions": ["filesystem.read"]\n} }',
  },
  businessImpact: [
    {
      title: "Files can be modified",
      description: "Read and write access to your filesystem",
    },
    {
      title: "Secrets can be exposed",
      description: "API keys and credentials within reach",
    },
    {
      title: "External systems can be contacted",
      description: "Outbound network and third-party APIs",
    },
  ],
  highestRiskPath: {
    id: "path-0",
    nodes: [
      {
        id: "reviewer.prompt",
        type: "prompt",
        name: "reviewer.prompt",
        isSink: false,
        edgeLabel: "probable",
      },
      {
        id: "tool-router.yaml",
        type: "tool-router",
        name: "tool-router.yaml",
        isSink: false,
        edgeLabel: "probable",
      },
      {
        id: "filesystem-mcp",
        type: "mcp-server",
        name: "filesystem-mcp",
        isSink: false,
        edgeLabel: "confirmed",
      },
      {
        id: "Filesystem write",
        type: "action",
        name: "Filesystem write",
        isSink: true,
      },
    ],
    severity: "high",
    confidence: "probable",
    fileCount: 3,
    confirmedFacts: "Secrets capability derived from direct executor evidence.",
    inferred:
      "Prompt names a sensitive action exposed by a configured MCP server.",
    filesInvolved: ["prompts/reviewer.prompt", ".cursor/mcp.json"],
    otherSensitiveActions: [
      { action: "Network", pathCount: 8 },
      { action: "Filesystem", pathCount: 9 },
      { action: "Shell", pathCount: 10 },
    ],
  },
  files: [
    {
      path: ".cursor/mcp.json",
      provenance: "configuration",
      artifactType: "MCP config",
      description: 'autoApprove:true + permissions:["*"]',
      pathRisk: "high",
      fileFinding: "high",
      issueCount: 4,
      pathCount: 11,
    },
    {
      path: "prompts/reviewer.prompt",
      provenance: "production",
      artifactType: "Prompt",
      description: "entry point of the highest-risk path",
      pathRisk: "high",
      fileFinding: "medium",
      issueCount: 2,
      pathCount: 9,
    },
    {
      path: "tools/tool-router.yaml",
      provenance: "configuration",
      artifactType: "Tool router",
      description: "routes prompt to filesystem-mcp",
      pathRisk: "high",
      fileFinding: "medium",
      issueCount: 1,
      pathCount: 6,
    },
    {
      path: "skills/code-review/SKILL.md",
      provenance: "production",
      artifactType: "Skill",
      description: "invokes filesystem-mcp",
      pathRisk: "medium",
      fileFinding: "low",
      issueCount: 1,
      pathCount: 14,
    },
    {
      path: ".github/workflows/ai-review.yml",
      provenance: "configuration",
      artifactType: "Workflow",
      description: "runs reviewer on every PR",
      pathRisk: "low",
      fileFinding: "low",
      issueCount: 2,
      pathCount: 12,
    },
    {
      path: "memory/reviewer-memory.json",
      provenance: "production",
      artifactType: "Memory",
      description: "persisted reviewer context",
      pathRisk: "low",
      fileFinding: "low",
      issueCount: 1,
      pathCount: 3,
    },
    {
      path: "README.md",
      provenance: "documentation",
      artifactType: "Doc",
      description: "excluded from verdict",
      pathRisk: "info",
      fileFinding: "info",
      issueCount: 1,
      pathCount: 0,
    },
  ],
  remediation: [
    {
      order: 1,
      title: "Restrict permissions to read-only",
      codeHint: '"permissions": ["filesystem.read"]',
      fileHint: ".cursor/mcp.json",
      impact: "high",
      effort: "medium",
    },
    {
      order: 2,
      title: "Disable auto-approval",
      codeHint: '"autoApprove": false',
      fileHint: ".cursor/mcp.json",
      impact: "high",
      effort: "low",
    },
    {
      order: 3,
      title: "Add approval gate before shell routes",
      codeHint: "require_confirmation: true",
      fileHint: "tools/tool-router.yaml",
      impact: "medium",
      effort: "medium",
    },
  ],
  evidence: [
    {
      file: ".cursor/mcp.json",
      line: 18,
      snippet: '"autoApprove": true',
      rule: "mcp_auto_approve",
      confidence: "confirmed",
    },
    {
      file: ".cursor/mcp.json",
      line: 9,
      snippet: '"permissions": ["*"]',
      rule: "mcp_wildcard_permission",
      confidence: "confirmed",
    },
    {
      file: "tools/tool-router.yaml",
      line: 12,
      snippet: "route: filesystem-mcp",
      rule: "tool_route_to_sink",
      confidence: "probable",
    },
    {
      file: "prompts/reviewer.prompt",
      line: 3,
      snippet: '"read and write any file"',
      rule: "prompt_unbounded_fs",
      confidence: "probable",
    },
    {
      file: "skills/code-review/SKILL.md",
      line: 22,
      snippet: "invokes filesystem-mcp",
      rule: "skill_invokes_sink",
      confidence: "potential",
    },
  ],
  nonProductionFindings: [
    {
      count: 24,
      label: "documentation findings",
      note: "In README and docs — examples, not live wiring",
    },
    {
      count: 127,
      label: "intentional fixture findings",
      note: "In test files deliberately built to trip rules",
    },
    {
      count: 9,
      label: "example-config findings",
      note: "Sample configs shipped for reference",
    },
  ],
  paths: [
    {
      id: "p0",
      nodes: [],
      severity: "high",
      confidence: "probable",
      fileCount: 3,
      confirmedFacts: "",
      inferred: "",
      filesInvolved: ["reviewer.prompt", "tool-router.yaml", "filesystem-mcp"],
    },
    {
      id: "p1",
      nodes: [],
      severity: "medium",
      confidence: "potential",
      fileCount: 3,
      confirmedFacts: "",
      inferred: "",
      filesInvolved: ["code-review/SKILL.md", "ai-review.yml", "filesystem-mcp"],
    },
    {
      id: "p2",
      nodes: [],
      severity: "medium",
      confidence: "potential",
      fileCount: 2,
      confirmedFacts: "",
      inferred: "",
      filesInvolved: ["reviewer.prompt", "filesystem-mcp"],
    },
    {
      id: "p3",
      nodes: [],
      severity: "low",
      confidence: "potential",
      fileCount: 2,
      confirmedFacts: "",
      inferred: "",
      filesInvolved: ["tool-router.yaml", "filesystem-mcp"],
    },
    {
      id: "p4",
      nodes: [],
      severity: "low",
      confidence: "potential",
      fileCount: 2,
      confirmedFacts: "",
      inferred: "",
      filesInvolved: ["README.md", "filesystem-mcp"],
    },
  ],
  graph: {
    nodes: [
      { id: "prompt", type: "prompt", name: "reviewer.prompt", col: 0, row: 0, isSink: false, isHot: true },
      { id: "wf", type: "workflow", name: "ai-review.yml", col: 0, row: 3, isSink: false, isHot: false },
      { id: "skill", type: "skill", name: "code-review", col: 1, row: 0, isSink: false, isHot: false },
      { id: "readme", type: "doc", name: "README.md", col: 1, row: 1, isSink: false, isHot: false },
      { id: "router", type: "tool-router", name: "tool-router.yaml", col: 1, row: 2, isSink: false, isHot: true },
      { id: "mcp", type: "mcp-server", name: "filesystem-mcp", col: 1, row: 3, isSink: false, isHot: true },
      { id: "mem", type: "memory", name: "reviewer-memory.json", col: 1, row: 4, isSink: false, isHot: false },
      { id: "fs", type: "action", name: "Filesystem", col: 2, row: 0, isSink: true, isHot: true },
      { id: "shell", type: "action", name: "Shell", col: 2, row: 1, isSink: true, isHot: false },
      { id: "net", type: "action", name: "Network", col: 2, row: 2, isSink: true, isHot: false },
      { id: "secret", type: "action", name: "Secrets", col: 2, row: 3, isSink: true, isHot: false },
      { id: "api", type: "action", name: "External API", col: 2, row: 4, isSink: true, isHot: false },
    ],
    edges: [
      { from: "prompt", to: "skill", isConfirmedRoute: false },
      { from: "prompt", to: "mem", isConfirmedRoute: false },
      { from: "prompt", to: "readme", isConfirmedRoute: false },
      { from: "skill", to: "readme", isConfirmedRoute: false },
      { from: "skill", to: "router", isConfirmedRoute: false },
      { from: "readme", to: "api", isConfirmedRoute: false },
      { from: "router", to: "net", isConfirmedRoute: false },
      { from: "mcp", to: "shell", isConfirmedRoute: false },
      { from: "mcp", to: "net", isConfirmedRoute: false },
      { from: "mcp", to: "secret", isConfirmedRoute: false },
      { from: "wf", to: "mcp", isConfirmedRoute: false },
      { from: "wf", to: "readme", isConfirmedRoute: false },
      { from: "prompt", to: "router", isConfirmedRoute: true },
      { from: "router", to: "mcp", isConfirmedRoute: true },
      { from: "mcp", to: "fs", isConfirmedRoute: true },
    ],
  },
};

export default SAMPLE_SCAN;
